import { WeatherApi } from '../src/typings/weatherApi';

export const weatherApiMocks: WeatherApi[] = [
  {
    town: 'Athens',
    status: 'Clear',
    temperature: '30.2C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '20%',
  },
  {
    town: 'Paris',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'London',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'Istanbul',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'Berlin',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'Brussels',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'Frankfurt',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
  {
    town: 'Chicago',
    status: 'Cloudy',
    temperature: '15.5C',
    humidity: '87%',
    pressure: '1000 Pa',
    windSpeed: '3 mPh',
    cloudCover: '40%',
  },
];
