version: 2

jobs:
  build:
    docker:
      - image: .circleci/node14
    working_directory: ~/MyApp
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test
      - run: typescript

